### ISSUE TITLE
Use the function Show Context i2 Analyze 4.0.0

### ISSUE THREAD

**Issue by Joai2** [IBM-i2/Analyze#22]
Hello

How can I implement the function show Context?

I changed the topology.xml with the true values:

```xml
<i2-data-source ar="false" id="daod2">
      <DataSource ScsSearchSupported="true" EdrsGetContextSupported="true" 
ScsNetworkSearchSupported="true" EdrsGetLatestItemsSupported="true" Version="0" 
ScsPresent="true" ScsFilteredSearchSupported="true" ScsBrowseSupported="true" Id="" 
ScsDumbbellSearchSupported="true" SesPresent="true" EdrsPresent="true">
        <Shape>DAOD</Shape>
        <Name>DAOD1</Name>
      </DataSource>
    </i2-data-source>
```

I added in ApolloServerSettingsDAOD.properties the class for the IExternalDataApadter and IExternalDataItemRetriever, also ExternalDataCreateStandardEDRSRetrievalBlock is set in true:

```properties
#---- The full class name of the IExternalDataAdapter to use, and its (optional) Guice modules
IExternalDataAdapter=com.example.ExampleDataAdapterSubset
IExternalDataAdapter.modules=

#----The full class name of the IExternalDataItemRetriever to use, and its (optional) Guice modules
IExternalDataItemRetriever=com.example.ExampleDataAdapterSubset
IExternalDataItemRetriever.modules=

#----Whether or not an External Data Retrieval Service retrieval block is automatically created
#----as part of the Subset Exploration Service ingestion process.
ExternalDataCreateStandardEDRSRetrievalBlock=true
```

And i am getting an error of Server not found:

```properties
[AVISO   ] Application {http://www.i2group.com/Schemas/2011-03-03/ExternalDataRetrievalService}ExternalDataRetrievalService#{http://www.i2group.com/Schemas/2011-03-03/ExternalDataRetrievalService}GetContext has thrown exception, unwinding now
java.lang.ExceptionInInitializerError
```

In com.example.ExampleDataAdapterSubset i have the code for GetContext:

```java
public ExternalDataContextResults getContext(Collection<ProvenanceGroup> provenanceGroups, int maxNumberOfItems,boolean shouldThrowIfTooManyItems) {
    	System.out.println("Get context: What!.. yeah, i'm going...");
		ExternalDataContextResults edcrResult = null;
		try {
			edcrResult = buildContextResults(provenanceGroups,maxNumberOfItems,shouldThrowIfTooManyItems);
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}		
		return edcrResult;
	}
```

The FullTextSearch works fine, is when i push the "Show Context" button when the error is shown.

Thanks.

**Comment by AamirShipton** [comment]
Hi Joai2,

Let's see if we can identify the problem. Could you please attach the i2 Analyze Liberty server logs and the rest of your code for getContext (in particular the buildContextResults method).

Thanks,
Aamir

**Comment by Joai2** [comment]
Hi AaamirShipton

This is the log of i2 Analyze Liberty:
[messages.log.txt](https://github.com/IBM-i2/Analyze/files/34123/messages.log.txt)

The code rest of the code is:

```
private ExternalDataContextResults buildContextResults(Collection<ProvenanceGroup> provenanceGroups,
			int maxNumberOfItems,
	        boolean shouldThrowIfTooManyItems) throws SQLException, InterruptedException{
		
		System.out.println(": buildContextResults");
//		System.out.println(": Size: provenanceGroups" + provenanceGroups.size());
//		System.out.println("ID Provenance: " + provenanceGroups.iterator().next().getId());
		
	    int totalItemCount = 0;
	    boolean complete = true;
	    final Collection<ContextResultMapping> contextItemGroups = new HashSet<ContextResultMapping>();
	    Collection<String> allResultKeys = new HashSet<String>();
	    Collection<String> itemIds = new HashSet<String>();
	    Query query = new Query();
	    
	    HashMap<String,String> itemIdsEnt = new HashMap<String,String>();
	    
	    
	    for (ProvenanceGroup provenanceGroup : provenanceGroups){
	        	
//	    	final Collection<String> keys = findKeysFromProvenanceGroup(provenanceGroup);

//	    	itemIdsEnt = queryDV.obtenerIdsRelacionH(keys);	        
	        
	        ContextResultMapping contextItemGroup = new ContextResultMapping(provenanceGroup.getId(),itemIdsEnt.keySet(),complete);	            	           
	        contextItemGroups.add(contextItemGroup);
	    }
	        	    
//	    Source source = queryDV.ejecutarQueryRelacionEntidadesH(itemIdsEnt);

//	    return new ExternalDataContextResults(source,contextItemGroups);
	    return null;
	}

```

**Comment by AamirShipton** [comment]
Hi Joai2,

A null return value from the getContext method is not valid, but your implementation always returns null. Therefore you will get errors.

The Javadoc should help you to understand what you need to return from the getContext method. It will be available to you by hovering over the method name in the code in Eclipse, or else you can find it here: http://ibm-i2.github.io/Analyze/docs/com/i2group/apollo/externaldata/edrs/IExternalDataItemRetriever.html#getContext-java.util.Collection-int-boolean-

Instead of using System.out.println to see what is happening, may I recommend you use the Eclipse debugger? That way you can use breakpoints to stop the code and study each of the current variables and their values at a specified point in the code. Doing this will also mean that the error will not yet have been thrown before you find out what you are returning from the getContext method.

**Comment by Joai2** [comment]
Hi Aamir

I checked the Javadoc, and i have nothing different in my project, i am still having the error.

I implemented the getContext in IAP 3.0.9 succesfully, i have the same code in that project, and with the version 4.0.0 i can't implement the same code. what have changed that doesn't allow me to implement the getContext?

**Comment by AamirShipton** [comment]
Joai2,

The getContext API hasn't changed since v3.0.9 so code that worked then will work in v4. However, null was never a valid return value for the getContext method, so your code, which always returns null, would never have shown an item's context in either version.
Between those two versions, however, there were large architectural changes ('write' & 'read' servers became a single 'core' server) and the toolkit scripts were rewritten in Gradle, as was Developer Essentials, meaning that there could be other issues with the environment, particularly if you're using the same machine. For example, have you restarted your HTTP Server since the last time you deployed (I recommend you do this now regardless of your answer)?

Given what you have said about using this code with v3.0.9, I have some questions for you:

Are you using the same machine to setup v4 that you used for v3.0.9?
If so, did you try to upgrade the v3.0.9 to v4, or did you start from fresh? (Upgrade is not supported for Developer Essentials.)
Are you still using the same schema that you used for v3.0.9?
Have you recreated your schema mapping JAR using v4 or did you copy it across from your v3.0.9 deployment?

Lastly, if you'd like to attach your code to this issue (that is, the entire com.example.ExampleDataAdapterSubset Java file and any other pertinent classes of your own that it calls) I would be happy to investigate the direct cause of the errors about instantiating ExampleDataAdapterSubset and casting it to IExternalDataRetrievalConnector.

**Comment by Joai2** [comment]
Hello Aamir

I have it working now, it was a problem with the ApolloServerSettingsDAOD.properties, i had:

'''properties

IExternalDataRetrievalConnector=com.example.ExampleDataAdapterSubset
IExternalDataRetrievalConnector.modules=

IExternalDataItemRetriever=com.example.ExampleDataAdapterSubset
IExternalDataItemRetriever.modules=

'''
The IExternalDataRetrievalConnector was interfering with the IExternalDataItemRetriever, it was looking for other method that i didn't have in the ExampleDataAdapterSubset, i only delete the IExternalDataRetrievalConnector and the code work just fine.

Thank you very much for the assistance.

I have doubt, how can i delete all the schema for the i2 Analyze and the DAOD and charge one completely different?

**Comment by AamirShipton** [comment]
Hi Joai2,

Glad to hear it.

To remove a schema and delete all of your data from the databases and lucene indexes, you should use the clearData command.

Now alter or replace the schema as you wish. If your schema now has a different file name, make sure that your ApolloServerSettingsMandatory.properties file in the common fragment still references the latest file name of your schema (see the property named SchemaResource).

You will also need to regenerate the mapping JAR (schema.jar, by default) that was created when you first ran addDaodDataSource for your DAOD project because it was based on your previous schema.
To do this, run the generateMappingJar command to replace the existing JAR in the DAOD project's fragment. I say replace, rather than duplicate, because you will experience problems if you leave two mapping JARs in your fragment at the same time, as they will conflict. Do not run addDaodDataSource twice for the same project against the same toolkit.

After the new mapping JAR is generated, run the deploy command again.

**Comment by Joai2** [comment]
Hello Aamir!

I changed the schema as you said, it's fine now.

Thank you!
