### ISSUE TITLE
How to create a new project

### ISSUE THREAD

**Issue by au-arena** [IBM-i2/Analyze#24]
Hi,

I am trying to create a connector for a postgres DB.

Once these steps are done : 
https://github.com/IBM-i2/Analyze/blob/master/documentation/developer_essentials_deploying.md 

What is the process to create a new connector project from scratch? (whar are the libraries, configuration files etc...)

Thank you

Aurélien

**Comment by AamirShipton** [comment]
Hi Aurélien,

I understand that you wish to create a DAOD connector, as opposed to any other type of connector. Below are some instructions that cover the creation of both new DAOD & DLD connectors. It's worth being precise when following these:


1) Create a new project directory as a peer to the examples by copying a similar, existing example project directory
(For you I recommend copying the da-subset-filesystem-example.)

2) Rename the new directory with your choice of name for the project; avoid spaces & special characters

3) Delete any temporary directories in the new project that were copied from the old project, for example, bin & build

4) In the new project directory, find and replace the old project name with the new project name across all directory/file names/contents, for example, .settings\org.eclipse.wst.common.component & .project

5) If the new project does not depend on a resource that the old project did depend on, remove all references to the dependency across all file contents, for example, .settings\org.eclipse.wst.common.component & .classpath
(For you this will likely mean removing references to da-example-common)

6) Add the new project name to the end of master\settings.gradle

7) If the project is a client project, such as DLD, add its name to the clientProjects variable in the ext block in master\build.gradle.
(DAOD projects are not client projects, so you can skip this step)

8) If the project depends on another resource (even if it's the same as the old project's dependency), create a project dependencies block for the new project in master\build.gradle, immediately after the existing similar blocks

9) Run the commands/follow setup instructions as were necessary for the old project (for example for DAOD: addDaodDataSource, set topology flags, deploy), modifying the project name in the instructions, where necessary
(See https://github.com/IBM-i2/Analyze/blob/master/documentation/developer_essentials_example_daod.md)

10) Test that the new project works in the same way as the example it was modelled after
(After deployment, start the server, open the Intelligence Portal, click Browse, change the data source to the new project and check to see that there are some Person entities and some links between them.)

11) Customise the code as needed
(Change the code to connect to the Postgres DB, instead of reading in an XML file, which the DAOD example currently does)

12) If the project’s directory structure has changed, update the Eclipse deployment assembly
(This is not recommended but if you do need to introduce new directories in the project, Eclipse will only deploy them to the server if you complete this step)


If any of the instructions are unclear, just ask and I'll explain further.
Aamir

**Comment by au-arena** [comment]
Hi Aamir,

thanks, it was helpful. I followed your instructions and I got stuck at step 9). 

### Manipulation

I did the first steps as described in https://github.com/IBM-i2/Analyze/blob/master/documentation/developer_essentials_example_daod.md , and when doing:

build -t deploy

### Result

(...)
 + configuration/environment/i2analyze/environment.properties [selected]:
   - wlp.home.dir='C:/IBM/i2analyze/deploy-dev/wlp'
   - java.home.dir='C:/IBM/i2analyze/deploy-dev/java'
   - apollo.data='C:/IBM/i2analyze/data-dev'
   - help.port.number='7001'

 + configuration/environment/http-server.properties:
   - http.server.home.dir='C:/IBM/HTTPServer'
   - http.was.module.dir='C:/IBM/WebSphere/Plugins/bin/32bits'
   - http.server.ssl.enabled='false'

 + configuration/fragments/common/WEB-INF/classes/ApolloServerSettingsMandatory.properties:
   - PrincipalProvider='com.i2group.apollo.security.WebSphereRoleBasedPrincipalProvider'
   - UserDataSourceProvider='com.i2group.apollo.security.SimpleUserDataSourceProvider'
   - UserActivityLogger='com.i2group.apollo.useractivitylogger.NoOpUserActivityLogger'
   - IExternalDataItemEditor='com.i2.iap.consulting.daod.common.editor.ExampleItemEditor'
   - IExternalDataItemRetriever='com.i2.iap.consulting.daod.rdbms.DataAdapterSubset'
   - IExternalDataSubsetLocator='com.i2group.apollo.externaldata.CreatingSubsetLocator'
   - IExternalDataAdapter='com.i2.iap.consulting.daod.rdbms.DataAdapterSubset'
   - IExternalDataDocumentSource='com.i2group.apollo.externaldata.documentstore.ExampleExternalDataDocumentSource'
   - IExternalDataItemEditor='com.example.ExampleItemEditor'
   - IExternalDataItemRetriever=<unset>
   - IExternalDataAdapter='com.example.ExampleDataAdapterSubset'
   - ChartingSchemesResource='test-chartingschemes.xml'
   - SchemaResource='test.xml'
   - SecuritySchemaResource='example-security-schema.xml'

============================================================
======================== ERRORS (1) ========================
 + configuration/fragments/common/WEB-INF/classes/ApolloServerSettingsMandatory.properties:
   - The "IExternalDataItemRetriever" property has not been set. This is required when EDRS is enabled.

============================================================

Validation failed. Correct errors, and review any warnings.
:daod-stendal:deploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':daod-stendal:deploy'.
> Process 'command 'cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.414 secs


### Questions

Information: 
Beforehand doing this current manipulation I copy/paste a clean SDK directory in i2analyze directory. Unfortunately we did previous tests that must have impacted file(s) somewhere up in the hierarchy (in i2analyze/toolkit ?). In particular 'test.xml' was used to test the declaration of a new schema and we don't want it to appear anymore.


**1) About ApolloServerSettingsMandatory.propertie**
Is the file 
- 'configuration/fragments/common/WEB-INF/classes/ApolloServerSettingsMandatory.properties:' (as mentioned in the error message)

the same as 

- C:\IBM\i2analyze\SDK\sdk-projects\master\build\toolkit\configuration\fragments\common\WEB-INF\classes\ApolloServerSettingsMandatory.properties   ?

and what should be the values?

**2) About the schema of  the example 'da-subset-filesystem-example'**

the documentation says : 

*"The command also creates a Java library that maps from platform-compatible XML to i2 Analyze items. Unlike in the "data load direct" project, the addDaodDataSource target of the build command automatically determines what schema the deployed platform is using, and performs the necessary configuration."*

How does this step work and what is the precise source and the target of this operation? (+location of files involved)

Thank you for your help,

Aurélien

**Comment by AamirShipton** [comment]
Warning: Any files that you have added to the i2analyze\toolkit directory will be copied into the "staged toolkit" master\build\toolkit. Therefore this could cause problems in your development environment. Personally I would recommend that you reinstall i2 Analyze cleanly, then paste the clean SDK directory into place before following the Developer Essentials instructions to deploy the development environment. To avoid doing this you could also manually undo the changes you made to the i2analyze\toolkit, assuming that you can remember them all.

1) Yes. When you run commands against the 'build.bat' script, you are issuing commands to the staged toolkit. Therefore the error message that tells you there is a problem in the configuration directory is referring to the configuration directory in the staged toolkit; master\build\toolkit\configuration\fragments\common\WEB-INF\classes\ApolloServerSettingsMandatory.properties

The error you are getting about the IExternalDataItemRetriever property not being set is almost certainly because you have not set the <i2-data-source> boolean flags in the topology.xml file before running deploy. Please see the part of the DAOD example's instructions immediately before it tells you to run deploy (point 5. "Edit the <i2-data-source> element ..." ). You should not need to change the values in ApolloServerSettingsMandatory.properties to make the example work.


2) The addDaodDataSource task depends on the generateMappingJar task. This means that when you execute addDaodDataSource, the toolkit first executes generateMappingJar, then addDaodDataSource. For DLD projects you don't need to execute addDaodDataSource, so instead you simply execute generateMappingJar directly. This means that the process of generating the mapping JAR file is the same (from the toolkit's perspective) for DLD and DAOD projects, but you execute different commands to make that process happen.

When you run addDaodDataSource for your project, and generateMappingJar is executed first, that task uses your schema as the source for the generatation of the XSDs and JAXB classes that make up the contents of the mapping JAR, which is the result of this task.
The schema is found here: master\build\toolkit\configuration\fragments\common\WEB-INF\classes.
The generated mapping JAR is, by default, found here: master\build\toolkit\configuration\fragments\YOUR-PROJECT\WEB-INF\lib\schema.jar

**Comment by au-arena** [comment]
Hi Aamir,

regarding the previous questions in the preceding post:

1) yes, I have modified the flags and it is ok

2) it is clear how the addDaodDataSource task works except one last thing:

Is there a central schema or one schema per datasource ? 

PS: apparently when modifying the value of the key "SchemaResource" in the file "ApolloServerSettingsMandatory.properties", the modification is not taken into account by the build commands if there already a schema stored in the GAR. A workaround is to delete the full database in the GAR but it is not optimal.

**Comment by AamirShipton** [comment]
There is one central schema. Each data source must use the same schema for the system to function properly, and for useful analysis to be performed on the data.

Regarding the SchemaResource property, this should be updated once you have modified your schema XML file using the Schema Designer program (but only if you altered the filename). When using the Schema Designer, first synchronise with your i2 Analyze deployment. That will enable the program to validate the changes you are making to the schema and ensure that you do not get a configuration that would require you to delete your data. Once you have completed making your schema changes, use the Schema Designer's upload functionality to push the new schema to i2 Analyze.
