### ISSUE TITLE
Explanation of ELP fields

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#30]
Is there a document that explains what the ELP (Entity Link Property) XML tags are?, I am not talking about the ones that are created within Schema Designer, those properties are designed by the person in charge of creating the schema, but the properties like:

- RetrievalBlocks
- RetrievalData
- CardProvenance
- etc

**Comment by TonyJon** [comment]
Hi John

The definitions for the tags you have mentioned  can be found  in the XSD's that are created when the generateMappingJar target is run for your project and I2 Analyze schema that you are using.

They are included in that Schema mapping jar as 

- schema1.xsd
- schema2.xsd
- schema3.xsd
- schema4.xsd

You can also find these in the WEB-INF\classes folder of the staged version of the project  which in a default windows Developer Essentials  installation would be under:

`C:\IBM\i2analyze\SDK\sdk-projects\master\build\toolkit\configuration\fragments\your-project-name`

If you want to see an example of what the content for our XML should be, you can load the XSD's into eclipse, schema4.xsd is the main one,  and get it to generate sample XML for you. 

If you decide to try this you should tick the following on the New XML File wizard page for Select Root Element:

- Create optional attributes
- Create optional elements
      Limit optional element depth to 10 (this is 2 by default)
- Create first choice of required choice
- Fill elements and attributes with data

In most cases there is not a need to fill all of this out in the XML you provide to us as we can infer it.

For example, the following is part of what one of our Developer Essentials Examples  generates:
```
<?xml version="1.0" encoding="UTF-8"?>
<QueryResult
	xmlns:tns="http://www.i2group.com/Schemas/2013-10-03/ModelData/Provenance">
	<Persons>
		<Person>
			<ItemId>p1</ItemId>
			<ItemVersion>0</ItemVersion>
			<SecurityTagIds>
				<SecurityTagId>UC</SecurityTagId>
				<SecurityTagId>OSI</SecurityTagId>
			</SecurityTagIds>
			<PropertyBags>
				<PropertyBag>
					<DateTimes>
						<DateTime>2014-01-01T12:00:00+00:00</DateTime>
						<DateTime>2014-01-21T12:00:00+00:00</DateTime>
					</DateTimes>
				</PropertyBag>
			</PropertyBags>
			<Cards>
				<Card>
					<tns:CardProvenance>
						<RetrievalBlocks />
						<OriginId Type="IAP.SDK.Example" Version="1">
							<Key>
								<String>data1.xml</String>
								<String>p1</String>
							</Key>
						</OriginId>
					</tns:CardProvenance>
					<Person_DateofBirth>1972-11-01T00:00:00+00:00</Person_DateofBirth>
					<Person_FullName>
						<Person_FamilyName>Windsor</Person_FamilyName>
						<Person_First_Given_Name>Harry</Person_First_Given_Name>
					</Person_FullName>
					<Person_Imagery>
						<Person_Image>
							<DocumentId>documents/picture1.jpg</DocumentId>
							<Name>picture1.jpg</Name>
						</Person_Image>
					</Person_Imagery>
				</Card>
			</Cards>
		</Person>
  </Persons>
</QueryResult>
```
You can see that we do not need to generate the RetreivalBlocks or RetrievalData in order to be able to import.

If you do want to go back out to the same external data source., for example to expand  from an item to see what is related to it, then there are configuration settings that will cause our code to add in the necessary retrieval block for you based on the contents of the OriginId.

Cheers
