### ISSUE TITLE
DAOD Working in Dev environment but not when I moved it to a Production environment

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#33]
I am working at a client with version 3.0.5.1 of IAP. We have 2 environments: Dev-essentials & Production. We have created a DAOD that works fine in the Dev-essentials environment. When we follow the steps for "going live", it deployed succesfully. However When I perform a search I can see the correct XML generated (I print to the console the ELP XML), however in the portal I see "No results".

In the Dev environment, the exact same search generates the exact same XML, and I do see the result in the portal.

Any thoughts? What could be wrong?

**Comment by TonyJon** [comment]
Hi

The XML you see being generated by your code will be converted to our internal data model using the definitions in the mapping jar that our generate-mapping-jar task creates.

If the mapping jar does not have mappings for the entity and link elements that you are returning then it will silently step over them and move on.

If you are seeing no errors then this could be what is happening.

Initially I would check that the deployed mapping jar in your war for your DAOD connector under the Websphere application server (read side) is up to date.

Another thing that could cause this would be if the secondary search that we do on the index for the items you return so that we can show highlighting is not finding matches using the search term you are giving.

This can happen for two main reasons:

1: Our search internal algorithm does not think that anything matches your search term.
2: The property that the search is matching on is not getting returned in your XML.

You can get around 1 and 2 by altering the search modes in our  ApolloServerSettingsDaodMandatory.properties file to 1 eg:

ExternalDataSourceSearchMode=1
ExternalDataSourceFilteredSearchMode=1

This will stop the secondary search but will also stop any highlighting in the results.

If 2 is the issue  you can choose to include the missing field instead of altering the search mode.


Another  possibility is that your user does not have the security rights to see the items that you have returned.

In this case check the security groups that your user is a member of and what rights they have and what security is being assigned to the items in your XML.

**Comment by johngid** [comment]
I had an IBM services person come and help. There were files that were not consistent between the systems, like different (although very similar) mostly in the security-schema and other files.
