### ISSUE TITLE
Problems deploying a DAOD from Dev-essentials to a production environment

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#34]
I am working with version 3.0.5.1 of IAP. I have built a DAOD that works in my dev-essentials environment. I have followed the instructions for "Going live" with the DAOD, and everything goes well until I try to start-all-applications again.

I have "BUILD SUCCESFUL" messages after the following commands:

On the write server:
deploy.py -s write -t update-application
deploy.py -s write -t install-http-server-config

On the read server:
deploy.py -s read -t update-application
deploy.py -s read -t provision-storage-and-messaging

And when I run the following command (back on the write server):
    deploy.py -s write -t start-all-applications

I get the following error:
[echo] WASX7017E: Se ha recibido una excepci¢n al ejecutar el archivo "E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\websphere/manage-application.py"; informaci¢n de excepci¢n: com.ibm.websphere.management.exception.ConnectorException
[echo] org.apache.soap.SOAPException: [SOAPException: faultCode=SOAP-ENV:Client; msg=Read timed out; targetException=java.net.SocketTimeoutException: Read timed out]

BUILD FAILED
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\application\manage-application.xml:65: The following error occurred while executing this line:
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\application\manage-application.xml:96: The following error occurred while executing this line:
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\application\manage-application.xml:104: The following error occurred while executing this line:
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\application\manage-application.xml:218: The following error occurred while executing this line:
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\common\was-utils.xml:147: The following error occurred while executing this line:
E:\IBM\iap-3.0.5.1\IAP-Deployment-Toolkit\scripts\common\was-utils.xml:92: Script 'E:\IBM\WebSphere\AppServer\bin\wsadmin.bat' failed.

**Comment by TonyJon** [comment]
Hi

Not much to go on from the snippet I'm afraid but  I can see the read timed out  SOAPException but  there could be a number of causes.

When you were deploying your DAOD connector , did you copy your write side Toolkit  to the read side server as it is the read side that DAOD connectors actually live on?

If you have done that then ...

Initially, if it is OK with the client, I would suggest that you stop our applications  by running 

**deploy.py -s write -t stop-all-applications**

from the scripts folder on the write server 

Then stop  read and write  WebSphere servers by issuing the following from their respective toolkit scripts folders :

**deploy.py -s write -t stop-was-server**
**deploy.py -s read -t stop-was-server**

Clear out the logs folders from the read and write servers so that we get fresh log files.

Restart the HTTP server to make sure any changes are  active.

Restart the WebSphere servers by running the following from their respective toolkit scripts folders:

**deploy.py -s write -t start-was-server**
**deploy.py -s read -t start-was-server**

Stop and re-start MQ by running the following from  the write server toolkit scripts folder:

**deploy.py -s write -t stop-queue-manager**
**deploy.py -s write -t start-queue-manager**

Re start the applications by running 

**deploy.py -s write -t start-all-applications**

See what happens.

If that  is not successful then if you zip up and send me the log folders  for the read and write servers I will take a look for you.

I will email you directly  so that you can send those to me if needed.

**Comment by johngid** [comment]
I had an IBM services person come and help. There were files that were not consistent between the systems, like different (although very similar) mostly in the security-schema and other files.
