### ISSUE TITLE
Is there a way to convert EntityType.Id to xml tag?

### ISSUE THREAD

**Issue by tbozik** [IBM-i2/Analyze#38]
Is there a way to convert the EntityType.Id (eg. ET5) to iap compatible xml tag (eg. Person) using SDK classes?
The same applies for PropertyType.Id (eg. PER6) to to iap compatible xml tag (e. Person_FamilyName).

The ItemTypeIdList passed to the search method of IExternalDataAdapter holds the EntityType.Id but I would need to know, that it is "Person" object to be able to query external system...

**Comment by boalesth** [comment]
Hi Tomas,

Depending on your use case presumably yes.... The Type IDs and the display names are all stored in the schema, so although it wouldn't use our SDK classes  you could probably create your own converter... however I wouldn't recommend doing this as the xsds are the source of truth, and the IDs are unique.

Thanks

Esther

**Comment by tbozik** [comment]
Hi Esther,
 there should be a build in transformation from xml tag name to Id to pass the data to portal, right? I was hoping to have a class that makes this translation in reverse order. The search method has an id as in input parameter, but we would need to have a xml tag name to assemble a valid query against the external source.

**Comment by TonyJon** [comment]
Hi Tomas

The schema mapping jar that is created  when you add your DAOD  data source or when you run the generateMappingJar task does do the mapping from XML tag name to internal Item and property id's as it is used to create the corresponding java class instances,but it does not go the other way unfortunately.

The item type Id's, and the property type ids that get passed in to the search method can be looked up in the i2A Schema XML to give you the display names that would help you to create your query. (These are not the same as the XML Tag names used when returning data to us).

How you mange this lookup is up to you, you may decide to parse the schema and get the mappings, or perhaps just create your own lookup in a static file.

That latter one may sound odd but the main thing is not to code those ids directly in to your app as they might change.

You will need to update any static look-ups you create when the schema is modified  if you decide to do that rather than parsing the schema itself into memory, but changing the schema when DAOD is involved will usually mean you have to re generate the main schema mapping jar anyway so there is always maintenance work with a schema change.

Cheers
