### ISSUE TITLE
Analyze 4.1.3 Audit Log

### ISSUE THREAD

**Issue by RichGitHub1** [IBM-i2/Analyze#40]
Is there a way to get the  logged user name so that use it in DAOD classes?

I've been following "developer_essentials_example_audit_file":

Previously to this, I deployed my DAOD in "i2analyze server" successfully.

--------------------------------------------------------------------------------------------
I added awc directory to Eclipse workspace, then I added awc app to "awc server"
I imported "awc-audit-example-common" to Eclipse workspace 
I imported "awc-audit-file-example" to Eclipse workspace 
I moddified "DiscoServerSettingsMandatory.properties" :
 ``` pre
    #AuditLogger=com.example.audit.CSVAuditLogger
    #AuditLogger=com.example.audit.DatabaseAuditLogger
    AuditLogger=com.example.audit.FileAuditLogger
    #AuditLogger=com.i2group.disco.audit.NoOpAuditLogger
    ```
In Enterprise Explorer, **awc**-> **Deployment Assembly**,  I added "awc-audit-example-common" and "awc-audit-file-example" projects.
I edited "topoloy" file to add fragments :
          <fragment name="awc-audit-example-common"/>
          <fragment name="awc-audit-file-example"/>
I executed "build -t deploy -s awc" command from master directory.
Is there a way to get the  logged user name so that use it in DAOD classes?

I've been following "developer_essentials_example_audit_file":

I imported awc directory to Eclipse workspace, then I added awc app to "awc server"
I imported "awc-audit-example-common" to Eclipse workspace 
I imported "awc-audit-file-example" to Eclipse workspace 
I moddified "DiscoServerSettingsMandatory.properties" :
 ``` pre
    #AuditLogger=com.example.audit.CSVAuditLogger
    #AuditLogger=com.example.audit.DatabaseAuditLogger
    AuditLogger=com.example.audit.FileAuditLogger
    #AuditLogger=com.i2group.disco.audit.NoOpAuditLogger
    ```
In Enterprise Explorer, **awc**-> **Deployment Assembly**,  I added "awc-audit-example-common" and "awc-audit-file-example" projects.
I edited "topoloy" file to add fragments :
          <fragment name="awc-audit-example-common"/>
          <fragment name="awc-audit-file-example"/>
I executed "build -t deploy -s awc" command from master directory.
--------------------------------------------------------------------------------------------

At this point, I am not getting any audit log.

I missunderstand how to implement IAuditLogger interface, if I implement this interface directly in ExampleDataAdapterSubset class, I get Exceptions when I perform searchs.

I have doubt about how to use awc-audit-file-example.

How can I retreive the username in fullTextSearch method, for example?

**Comment by boalesth** [comment]
Hi Rich,

The DAOD implementation that we provide is in the i2Analyze server. The auditing example is in the awc server. As such, the auditing that we are providing is on the search functionality that is implemented in the awc application and not the i2Analyze.

Although we do not currently provide an example of the i2 implementation, we do provide an overview in the [IBM Knowledge Center.](https://www.ibm.com/support/knowledgecenter/beta/SSXVXZ/com.ibm.i2.understanding.doc/logging_and_auditing.html)

For more information about data logging, see the entry for the [IAuditService](http://ibm-i2.github.io/Analyze/docs/com/i2group/apollo/auditservice/IAuditService.html) interface in the i2 Analyze Java API documentation.

That bad news aside, your post starts by asking how you get to the logged user name so that it can be used in your DAOD implementation. The short answer to this is by injecting the 
[IPrincipalProvider] (http://ibm-i2.github.io/Analyze/docs/com/i2group/apollo/securityapi/IPrincipalProvider.html) into your implementation.

You can see what class we are using to implement our IPrincipalProvider by looking in ApolloServerSettingsMandatory.properties

Our implementation of this uses the standard J2EE java.security.principal and gives you access to this via an identifyPrincipal method.

It also provides two other methods called  determinePrincipalAccessRights and determinePrincipalGrantRights which, as you might expect, give you the i2 Analyze Access and Grant rights lists for this principal.

If for example, you wanted to add this to the ExampleDataAdapterSubset class in the `da-arload-filesystem-example`, to get the name from the principal you could: 

Import the required libraries:
```

import javax.xml.transform.Source;
import javax.xml.transform.stream.StreamSource;

import com.i2group.apollo.externaldata.adapter.IExternalDataAdapter;
import com.i2group.apollo.networksearchservice.transport.NetworkSearchNodeList;
import com.i2group.apollo.searchservice.transport.FilterInfoList;
import com.i2group.apollo.searchservice.transport.ItemTypeIdList;
import com.i2group.apollo.searchservice.transport.SearchNode;
import com.i2group.apollo.searchservice.transport.SetInfo;
 import com.google.inject.Inject;
import com.i2group.apollo.securityapi.IPrincipalProvider;

/**
 * An external data adapter that supports text searches and filtered searches
 * against information in an external XML file.
 */
public final class ExampleDataAdapterSubset implements IExternalDataAdapter
{
    private static final String XSLT_FILE_NAME = "dataToI2analyze.xslt";
    private static final String DATA_FILE_NAME = "data1.xml";
    private static final String NOT_SUPPORTED = "This operation is not supported";
    private final String mUserName;

```
and create a constructor and inject the principal provider like this.

 ```
   @Inject 
    public ExampleDataAdapterSubset (IPrincipalProvider principalProvider) 
    {
      mUserName = principalProvider.identifyPrincipal().getName();
    }
```

Due to the infrastructure we have in place this @Inject will give you the current instance of the principal provider for your users session.
Thanks

Esther
