### ISSUE TITLE
Analyze 4.1.3 deploying Error

### ISSUE THREAD

**Issue by dogbally** [IBM-i2/Analyze#41]
<Toolkit Version: 4.1.3.0-2141, Date Format: MM/dd/yyyy HH:mm:ss>
:configureToolkitExample
BUILD SUCCESSFUL
Total time: 7.218 secs
============== Configuration Summary (brief) ===============
+ configuration/fragments/common/WEB-INF/classes/ApolloServerSettingsMandatory.properties:
- ChartingSchemesResource='law-enforcement-schema-charting-schemes.xml'
- SchemaResource='law-enforcement-schema.xml'
- DynamicSecuritySchemaResource='example-dynamic-security-schema.xml'
============================================================
:configureExampleSolrCredentials
:configureToolkitExample
:ensureExampleUserInUserDetailsFile SKIPPED
:generateCredentialsFile
:validateDatabaseCredentials
:validateLTPAPassword
:validateSSLPassword
:validateSolrCredentials
:ensureCredentialsEncoded
:stopSolrWithoutError
Stopping Solr Node WIN:8983
No Solr found running on port 8983
:stopLibertyWithoutError
Server awc does not exist.
:ensureLibertyStopped
:installJava
IBM Java installation up-to-date, skipping installation. <Version: pwa6480sr3fp20-20161019_02(SR3 FP20)>
:installJava SKIPPED
:installLiberty
IBM WebSphere Liberty Profile installation up-to-date, skipping installation. <Version: 16.0.0.3>
:installLiberty SKIPPED
:ensureSolrStopped
:ensureZookeeperStopped
:installSolrInternal
Apache Solr installation up-to-date, skipping installation. <Version: 6.2.1>
:installSolrInternal SKIPPED
:addSolrExtJars
Adding jars to Solr ext
Database directory or system database directory.
:ensurePreReqsUpToDate
:copyFindPathSar
:generateInfoStoreCreationScripts
:generateInfoStoreDataTableCreationScripts
:beforeDatabasesCreated
:createDatabasesIfNecessaryInternal
Finding data sources in application.
Number of matching data sources found: 1
Generating resources.properties in: C:\IBM\i2analyze\toolkit\scripts\gradle\build/database-resources
Executing action 'CREATE_STORAGE' against data source: istore
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\ar.version.properties
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\ccconfig.version.properties
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\infostore.version.properties
Version information loaded
Creating storage for database: ds/InfoStore-infostore
Executing SQL script "C:\IBM\i2analyze\toolkit\scripts\database\db2\InfoStore\create-database-storage.db2".
Executing script with DB2 command-line processor.
Command: C:\Program Files\IBM\SQLLIB\bin\db2 -td@ -f C:\Users\Administrator\AppData\Local\Temp\iap.6607823855692523604.create-database-storage.db2
SQL1005N  The database alias "istore" already exists in either the local
database directory or system database directory.
Assuming that the database already exists.
Finding data sources in application.
Number of matching data sources found: 1
Generating resources.properties in: C:\IBM\i2analyze\toolkit\scripts\gradle\build/database-resources
Executing action 'UPGRADE' against data source: istore
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\ar.version.properties
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\ccconfig.version.properties
Loading version information from C:\IBM\i2analyze\toolkit\scripts\database\infostore.version.properties
Version information loaded
java.lang.IllegalStateException: InfoStore 'infostore' is in an invalid state. It has a 'DATABASE_VERSIONS' table (so it must be version 3.0.5.0 or later), but the table is empty.
:createDatabasesIfNecessaryInternal FAILED
FAILURE: Build failed with an exception.
* Where:
Script 'C:\IBM\i2analyze\toolkit\scripts\gradle\database.gradle' line: 222
* What went wrong:
Execution failed for task ':createDatabasesIfNecessaryInternal'.
> Process 'command 'C:\IBM\i2analyze\toolkit\tools\java\bin\java.exe'' finished with non-zero exit value 1
BUILD FAILED

I have got an error end of the code...Can you help me, please? Thanks

**Comment by TonyJon** [comment]
Hi
The error you are experiencing is often due to the Information Store  being left in an inconsistent state  after an earlier failure. (Which may have now been fixed by yourself). 

To check this it would be worth you dropping the Information Store  database from db2,  as long as you have no data records in it that you need to keep, and then re running your current command.

Are you trying to deploy one of the Developer Essentials  Information Store Examples or is it a standard i2 Analyze deployment toolkit Information Store deploy that you are doing?

For a standard i2 Analyze deployment toolkit you will be running **setup** from here:
**C:\IBM\i2analyze\toolkit\scripts**

so you should run 
**setup -t dropDatabases -s awc**
from that folder.

For a Developer Essentials  example deployment you would be running **build** from here:
**C:\IBM\i2analyze\SDK\sdk-projects\master**

so you should run 
**build -t dropDatabases -s awc**
from that folder.

Usually queries here are Developer Essentials related.

When you have run one of those commands depending on your usage of the product, you can then re try  your failing operation. If the original issue has been fixed, it should complete correctly  but if not we should then see what the original problem was.

Cheers

**Comment by dogbally** [comment]
I made you say...bu I could not resolve the problem? 

noe: kit is standard i2 Analyze deployment toolkit

**Comment by TonyJon** [comment]
Hi

As this is a Standard I2Analyze  Information Store Deployment issue, we should handle this through different channels.

As I mentioned above, GitHub is used for Developer Essentials related queries.

If you are an Internal IBMer you can raise your problem on our internal i2 Community of Practice  Wiki here: https://w3-connections.ibm.com/communities/service/html/communitystart?communityUuid=813b75ea-78ac-4ab1-97b9-151b5727e119)

If you are an external  business partner or customer then please contact  IBM support in the normal way and we can continue to help you resolve your issue.

Cheers

**Comment by dogbally** [comment]
ok thanks
