### ISSUE TITLE
ItemTypeId to "displayName"?

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#46]
Hi, 

The team I am working with are implementing the dumbbellSearch method in a custom DAOD. From the searchNode, we are able to get the TypeId that corresponds to the entity we are performing our search. However this is just the Id (like "ET5").

I am looking for a way of getting what Entity is represented by ET5. I am looking for the best way to do this (without unpacking the schema.jar). There may be a different apptoach, however, looking through the APIs, I see that there is a way of getting the schema as an object (from a schemaResult), from there getting the ItemType list, and from there we can probably iterate and find ET5.

Is there a better way to do this?, could you provide an example that returns the Schema object?

Regards 
John

**Comment by TonyJon** [comment]
Hi John

There isn't a **published**  neat way of doing this I'm afraid.

You can use the schemaResult from the Admin Service but to do that you would need to use our Java Client to instantiate an instance for you to use and that would require  re submitting credentials, creating a new session etc in order to make the connection. Using the services like that also tends to done  by applications that are not already within the application server. Another disadvantage of using the Admin service is that you need to provide  credentials for an i2 Administrator  as well. 

The infoservice  is a slightly better option as that  gives you access to a DataSourcesAndSchema method  and you do not have to be an i2 Administrator to run it  but again it still needs our Java Client and re authentication etc as above.

The Schema in i2 Analyze  should change fairly infrequently once the dust has settled on a deployment and often when schema changes are  made  that can mean updates to  XSLT  mappings or connector code and will require the  mapping schema.jar to be  re generated.  You could take the view therefore that  the schema is effectively static  and write something  (XSLT or java code for example) to  iterate the xml file that contains the schema definition and create a configuration file for you that gives an easy look up for your code to use. (FYI Schema.jar doesn't actually contain the schema it contains XSD's and mapping classes  define our XML format and how we load our classes from that).

Alternatively the schema that is in use by the running application is  available as a resource on the class path so you could use  JAXB  for example to load from that when you  run your DAOD connector  and create an in memory map  to use.

I am assuming here that you are trying to get from the  id's we give in our parameters for the search  to the display names   of the items and properties. If that is not the case let me know.

Cheers
