### ISSUE TITLE
How to hide DAODs in menu

### ISSUE THREAD

**Issue by johngid** [IBM-i2/Analyze#47]
I would like to know how to enable or disable certain DAODs from certain searches. For example, I have 3 DAODs, and I would like to only show 1 on the "FullTextSearch" box. I want specific ones in ANBP to showContext, and potentially a different list in different searches (like visual query and property search).

I understand this is done in the topology file, in the DataSource tag, where we have something like this:

   ```
<DataSource ScsSearchSupported="true" EdrsGetContextSupported="false" 
               ScsNetworkSearchSupported="false" EdrsGetLatestItemsSupported="false"  
               Version="0" ScsPresent="true" ScsFilteredSearchSupported="false" 
               ScsBrowseSupported="true" Id="" ScsDumbbellSearchSupported="false" 
               SesPresent="true" EdrsPresent="false"
               >
```

Which attribute enables or disables the DAOD in what type of search? Is there documentation for each of these tags?

I appreciate the help. Regards
John

**Comment by TonyJon** [comment]
Hi John

This is some information on what the different settings  in the DAOD data source definition in the topology file mean. 


I have linked each data source search option to its Portal  UI elements and to the API call on your implementation of IExternalDataAdapter and IExternalDataItemRetriever so hopefully this will help.

**DAOD data source  from topology file:**

This defines whether or not a data source is used as the default and also defines what sort of data source it is.

![image](https://user-images.githubusercontent.com/17141806/33895194-dd58b968-df57-11e7-9208-970b182be208.png)


This definition is used generate a data source configuration that is used by the portal code to determine what search functions should offer the this data source as a choice and  whether it is the default used in the Portal.

**The search service definitions:**

**EdrsPresent="true"** Whether the external data retrieval service is supported
**SesPresent="true"**  Whether subset exploration service functionality is supported.
**ScsPresent="true"** Whether subset creation service functionality is supported.

For a standard  DAOD data source running from a native Portal (not a customized UI) SCS and SES will always be true as these two are fused together in this implementation. EDRS is true depending on whether you want to implement the secondary retrieval service to the external source for getContext and getLatestItems.

This is why you do not see options for switching SES functionality on or off separately.

**The search option definitions:**

These define which search options are available for your  data source and therefore which ones you need to implement.

**ScsBrowseSupported="true"** This enables browsing with your data source in the Portal and will mean that calls will be made to the "fullTextSearch" method on your implementation of IExternalDataAdapter with an empty string parameter.  We do not recommend allowing browsing on DAOD data sources due to the possibly high volume of data that could be returned. In order to stop a normal fullTextSearch being used for browsing you should code your implementation to not run a "get me everything search"  when  it sees an empty string and set ScsBrowseSupported = "false".  You can not stop a datasource being available as a choice  for browse  using this  option but it will not actually run and you will just be told that it is not supported.
 
![image](https://user-images.githubusercontent.com/17141806/33894779-b91127bc-df56-11e7-9121-0014c2821bae.png)
    

**ScsSearchSupported="true"**  This enables fuzzy text searching and will make your data source a choosable option for this in the Portal and will mean that calls will be made to the "fullTextSearch" method on your implementation of IExternalDataAdapter 

![image](https://user-images.githubusercontent.com/17141806/33894827-da38170c-df56-11e7-8c32-29e278434c5c.png)


**ScsFilteredSearchSupported="true"** This enables basic single entity property based searching making your data source choosable in this mode and will mean that calls will be made to the "search" method on your implementation of IExternalDataAdapter. 
 
![image](https://user-images.githubusercontent.com/17141806/33894864-f68738fc-df56-11e7-9746-19b561b48c71.png)


It also allows you to use the entity type filter option with Fuzzy search too. Just to confuse things, if you have this and  ScsSearchSupported set to true and do a fuzzy search with a  type filter it will actually call "search" not "fullTextSearch". 
 
![image](https://user-images.githubusercontent.com/17141806/33894887-06b2b27e-df57-11e7-986f-e6605a58029e.png)


**ScsDumbbellSearchSupported="true"** This enables the  Entity Link Entity extension to property based searching and will mean that calls will be made to the "dumbbellSearch" method on your implementation of IExternalDataAdapter if you select more than just a single entity when you configure your property based search. 
 
![image](https://user-images.githubusercontent.com/17141806/33895008-531a8a42-df57-11e7-8aa7-432f75d29f2a.png)


**ScsNetworkSearchSupported="true"** This enables Visual Querying making your data source choosable in this mode and will mean that calls will be made to the "networkSearch" method on your implementation of IExternalDataAdapter 
 
![image](https://user-images.githubusercontent.com/17141806/33895035-63c2c94a-df57-11e7-877a-46ffe04cd520.png)


**EdrsGetContextSupported="true"** This enables the "Show Context" option for entities  that originate from your data source and replaces "Expand" in menus in both the Portal and ANBP for these items and will mean that calls will be made to the getContext method you implement for IExternalDataItemRetriever. 
 
**EdrsGetLatestItemsSupported="true"** This has no effect on Portal operations as the portal does not make use of getLatestItems but it is necessary when you do a getContext from ANBP and when you send items to ANBP from the portal. ANBP checks that the item /items you have selected  still exist in the external source by calling getLatestItems on the IExternalDataItemRetriever before it does anything with them and without this implementation you will get an error. 

If you have questions on any of this feel free to ask.
